version: "3"

services:
  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=neo4j/nehtgraff
    ports:
      - 7687:7687
      - 7474:7474
      - 7473:7473
    volumes:
      - /home/dev/PycharmProjects/neht-graff/data/csv:/var/lib/neo4j/import
    restart: always

